services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "LATEST"
      MEMORY: "8192M"
      MOTD: "Someone get Adam a Twisted Tea"
      TZ: "America/Chicago"
      DIFFICULTY: "2"
      ENABLE_WHITELIST: "true"
      RCON_CMDS_STARTUP: |-
        /scoreboard objectives add Deaths deathCount
        /scoreboard objectives setdisplay list Deaths
      ALLOW_FLIGHT: "true"
    volumes:
      - "/mnt/nas/mc_au2:/data"

