---
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central
      - VERSION=docker
      # - PLEX_CLAIM= #optional
    ports:
      - "32400:32400"
    volumes:
      - /mnt/nas/plex:/config
      - /mnt/anime:/anime
    restart: unless-stopped
  shoko_server:
    shm_size: 256m
    image: ghcr.io/shokoanime/server:latest
    container_name: shoko_server
    network_mode: host
    environment:
      - "PUID=1000"
      - "PGID=100"
      - "TZ=US/Central"
    ports:
      - "8111:8111"
    volumes:
      - "/mnt/nas/shoko:/home/shoko/.shoko"
      - "/mnt/nas/anime:/mnt/anime"
    restart: unless-stopped
   
